name: Test branchMatchRegex Action

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '24'

      - name: Test with single pattern
        uses: ./
        with:
          patterns: '.*'

      - name: Test with list
        uses: ./
        with:
          patterns: |
            - feature/*
            - fix/*
            - hotfix/*
            - docs/*
            - test/*
            - refactor/*
            - style/*
            - ci/*
            - perf/*
            - i18n/*
            - security/*
            - release/*
            - chore/*
            - test/*
            - renovate/*

      - name: Test with inline list
        uses: ./
        with:
          patterns:
            "['feature/*', 'fix/*', 'hotfix/*', 'docs/*', 'test/*',
            'refactor/*', 'style/*', 'ci/*', 'perf/*', 'i18n/*', 'security/*',
            'release/*', 'chore/*', 'test/*', 'renovate/*']"

      - name: Test with file
        uses: ./
        with:
          path: .github/branches.yml

      - name: Test with file
        uses: ./
        with:
          useDefaultPatterns: true

      - name: Test with file and branch name
        uses: ./
        with:
          useDefaultPatterns: true
          branch: 'feature/test'

      - name: Test with URL
        uses: ./
        with:
          path: 'https://raw.githubusercontent.com/IamPekka058/branchMatchRegex/main/assets/default-patterns.yml'
